### PR TITLE
log -> logging + compiler flags

### PR DESCRIPTION
**Pull request by NukeWilliams**
hey @krishpranav I have added these changes

enable log -> enable logging + added compiler functions

### CODE REVIEW

**Comment by krishpranav** [comment]
hey @NukeWilliams this is the first pr of this project now only I just created the organization and created this repo thanks for this pr and your changes were good!!

**Comment by krishpranav** [comment]
__MERGED__

**Review by krishpranav — COMMENTED** [review]
great one

**Comment by NukeWilliams** [comment]
my pleasure

**Pull request merged**
